### ISSUE TITLE
'window is not defined' error while SSR

### ISSUE THREAD

**Issue by ikappas** [lifeiscontent/react-svg-injector#1]
This following error is thrown while server side rendering the react app:
```bash
/projects/testing/test-app-ts/node_modules/svg-injector/svg-injector.js:464
}(window, document));
  ^

ReferenceError: window is not defined
    at Object.<anonymous> (/projects/testing/test-app-ts/node_modules/svg-injector/svg-injector.js:464:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)    at require (internal/module.js:11:18)
    at Object.svg-injector (/projects/testing/test-app-ts/build/server.js:3549:18)
    at __webpack_require__ (/projects/testing/test-app-ts/build/server.js:630:30)
```

This can be easily fixed by changing:
```js
import SVGInjector from 'svg-injector';
```
with
```js

const isBrowser = typeof window !== 'undefined';
const SVGInjector = isBrowser ? require('svg-injector') : undefined;

```

See also:
https://github.com/webpack/react-starter/issues/37#issuecomment-104304128
https://github.com/atomic-app/react-svg/issues/15

**Comment by lifeiscontent** [comment]
@ikappas published 1.0.1 with the fix.

**Comment by ikappas** [comment]
@lifeiscontent The fix did not make it into dist

**Comment by lifeiscontent** [comment]
@ikappas sorry about that! Just added a `prepublishOnly` step to the package.json so I don't forget next time.

Let me know if it works for you. Just published 1.0.2

**Comment by ikappas** [comment]
@lifeiscontent works like a charm! Thank you! 👍

**Comment by lifeiscontent** [comment]
@ikappas not sure if this simplifies your case, but I decided to use this instead of this lib: https://github.com/lifeiscontent/react-mutate-icon rather than dealing with loading SVGs, you can create a object with react components built from `svgr` and do the same manipulation from this library without waiting for the icons to load.
